<p>Hej <?= $this->participant->getName()?>,</p>

<p>
  Du modtager denne mail, fordi du er en af de fantastiske arrangører på årets Fastaval, og vi mangler stadig at modtage dit billede til dit navneskilt.
</p>

<p>
  Vi vil rigtig gerne give dig et flot ID-kort, så du kan få dine velfortjente rabatter på kongressen. Da billedet på kortet kun bliver ca. 3 cm højt på print, har vi brug for din hjælp til at gøre det så tydeligt som muligt. Det sparer os for en masse manuel efterredigering og sikrer, at salgsstederne nemt kan se, hvem du er!
</p>

<p><strong>For at dit billede kan bruges, skal det leve op til disse krav:</strong></p>
<ul>
  <li><strong>Portrætfoto:</strong> Det skal være et billede af dig alene - ikke et gruppebillede.</li>
  <li><strong>Vellignende:</strong> Billedet skal være skarpt og uden filtre, ansigtsmaling eller masker.</li>
  <li><strong>Kig ligefrem:</strong> Dit ansigt skal være tydeligt synligt, godt oplyst og vendt mod kameraet.</li>
  <li><strong>Lys baggrund:</strong> Tag gerne billedet mod en lys og ensfarvet væg.</li>
</ul>

<p>
  <strong>Vigtigt ved upload:</strong> Når du har valgt dit billede, skal du bruge slideren til at beskære det, så dit ansigt fylder <strong>ca. 80% af højden</strong> i rammen.
</p>

<p>Du kan uploade dit billede her:</p>
<p><a href="<?= $this->link;?>"><?= $this->link;?></a></p>

<p>
  <strong>Deadline er i aften kl. 22.00</strong>.<br />
  Husk at dit arrangørkort er et ID-kort og et privilegie. Hvis du ikke har uploadet et billede, der lever op til kravene inden deadline, bliver kortet printet uden billede, og du vil derfor ikke kunne få rabat under Fastaval.
</p>

<p>
  Hvis teknikken driller her på falderebet, så beklager vi meget. Kontakt os hurtigst muligt på 
  <a href="mailto:it@fastaval.dk">it@fastaval.dk</a> og send meget gerne dit billede med, så ser vi om vi kan nå at hjælpe dig.
</p>

<p>
  Vi glæder os helt vildt til at se dig i Hobro!
</p>

<p>
  Venlige hilsner<br/>
  Fastaval-teamet
</p>