<h2>Payment reminder for Fastaval <?= $this->year ?></h2>

<p>Hi <?= $this->participant->getNickname() ?>,</p>

<p>
  We are writing to you because we haven't registered a payment from you for Fastaval <?= $this->year ?> yet, and
  we would therefore like to remind you to complete your payment.
</p>

<p>Did you already pay?</p>
<ul>
  <li>If you payed very recently, you can ignore this mail, since we probably just need to update our records</li>
  <li>
    If you payed several days ago, we would very much like you to contact us at <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>,
    so we can register your payment correctly.
  </li>
</ul>

<p>
  If you haven't paid yet, please remember that the deadline for your payment is <?= $this->payment_day_en; ?>.
  If we do not receive your payment by this date, ordered items (wear) and food will be removed from your registration.
  This is due to our ordering process, as we require pre-payment for these items. Your general registration for
  Fastaval will remain active, and you can pay at the entrance.
</p>

<p>
  <?php if ($this->participant->betalt_beloeb == 0) : ?>
    The total amount for your registration is <strong><?= $this->payment_remainder ?></strong> DKK, which is due on <?= $this->payment_day ?>.

  <?php else : ?>
    You have already paid <?= $this->participant->betalt_beloeb ?> DKK, but it looks like you still owe us
    <strong><?= ($this->payment_remainder) ?></strong> DKK<br />
  <?php endif; ?>
</p>

<p>
  We have a new payment system provided by Bifrost, thus it will be their name showing in the payment window.
  You can pay using our new payment system by following this link:<br /><br />
  <a href="https://www.fastaval.dk/26tilmelding/paynow?hash=<?= $this->participant->participant_hash ?>">Pay online</a><br />
  (The payment will be registered instantly at our provider, but it will take a few days to transfer the data to our own system, since it's a manual process)
</p>

<p>
  When using any other form of payment, it's important that you note both name and participant ID, which is: <strong><?= $this->participant->id ?></strong>
</p>

<h4>Payment by bank transfer</h4>
<p>
  It is also possible to pay via bank transfer. Please note that there is a fee of <?= e($this->banking_fee); ?> DKK
  for this option as it requires manual handling. Additionally, international bank transfers usually incur extra fees from the banks.
  <b>All fees incurred on international transfers are your responsibility.</b>
</p>

<p>To pay by bank transfer, please use the following details:</p>
<ul>
  <li>
    <strong>Amount due:</strong> <?= e($this->payment_remainder + floatval($this->banking_fee)); ?> DKK
    (<?= e($this->payment_remainder); ?> DKK + <?= e($this->banking_fee); ?> DKK fee)
  </li>
  <li><strong>Danish bank:</strong> Reg.: 9070 / Account: 1638710893</li>
  <li><strong>International bank:</strong> IBAN: DK1090701638710893 and BIC: VRSPDK22</li>
  <li>
    <strong>Message:</strong> ALWAYS include your name and participant ID <strong><?= $this->participant->id ?></strong>
    so we can register your payment correctly.
  </li>
</ul>

<p><strong>We look forward to seeing you at Fastaval <?= $this->year ?>!</strong></p>
<p>Best regards,</p>
<p>Fastaval</p>