<style>
  :root {
    color-scheme: light;
  }

  div.section {
    max-width: 81.5%;
    margin: auto;

    color: #000000;
    background-color: #f9ad1b;
    padding: 1rem;
    border-radius: 10px;

    margin-bottom: 2rem;
  }

  div.section h2 {
    text-align: center;
    margin-top: 0;
  }

  div.section table {
    margin: auto;
  }
</style>

<div id="content" style="max-width: 800px; margin: auto; font-family: Arial, Helvetica, sans-serif;">
  <img src="https://infosys.fastaval.dk/img/banner-2026-transparent.png" style="width: 100%"/>
  
<div class="section">
  <h1>Hi <?=$this->name?>,</h1>
  
  <p>
    Fastaval is just around the corner! The hype is building, and it's finally time to reveal your personal Fastaval
    schedule. But first, here is some essential info to get you ready.
  </p>
</div>

<div class="section">
  <h2>Practical information</h2>
  
  <p>
    You can find everything you need to know about transport, house rules, and opening hours on our 
    <a href="https://www.fastaval.dk/en/practical-information/">Practical information</a> page.
  </p>
  
  <p>
    If you have questions about Fastaval, please contact <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>
  </p>
  
  <p>
    If you need a Safety Host (Tryghedsvært) at any point, call or text <strong>+45&nbsp;93&nbsp;90&nbsp;35&nbsp;67</strong>.</br>
    You can read more about our safety initiatives on our <a href="https://www.fastaval.dk/en/well-being-and-safety/">Well-being and Safety</a> page.
  </p>
  
  <p>
    AFor urgent matters, the General on Duty is available at <strong>+45&nbsp;93&nbsp;90&nbsp;35&nbsp;69</strong>.
  </p>
</div>
  
<div class="section">
  <h2>New to Fastaval</h2>
  
  <p>
    If this is your first time (or you just need a quick refresher), come join our <strong>Intro Tour</strong>. It's a
    great way to get your bearings, ask questions, and meet fellow newcomers. We meet at the <strong>Info Desk</strong>
    in the common area at these times:
  </p>
  
  <table>
    <tr>
      <td>Wednesday:</td><td>5:30 pm</td>
    </tr>
    <tr>
      <td>Thu - Sat:</td><td>10:00 am</td>
    </tr>
  </table>
</div>

<div class="section">
  <h2>Check in when you arrive</h2>
  
  <p>
    When you arrive, head to the <strong>Info Desk</strong> by the main entrance of Mariagerfjord Gymnasium to check in.
    Here you'll receive a wristband for access to the convention. The Info Desk is open:
  </p>
  
  <table>
    <tr>
      <td>Wednesday:</td><td>3:00 pm - 8:30 pm</td>
    </tr>
    <tr>
      <td>Thu - Sat:</td><td>09:30 am - 8:30 pm</td>
    </tr>
    <tr>
      <td>Sunday:</td><td>09:30 am - 5:00 pm</td>
    </tr>
  </table>
  
  <p>
    If you signed up before the deadline, your physical name badge will also be waiting for you here.
  </p>
  
  <p>
    You can also pick up badges at the Info Desk to indicate your preferred language, pronouns, or "sober status" to
    help everyone feel comfortable.
  </p>
</div>

<div class="section">
  <h2>The Big Clean-up</h2>
  
  <p>
    If you're still at Fastaval on <strong>Monday, April 6th, after 9:30 AM</strong>, we ask that you lend a hand with
    the clean-up. Even just an hour of help makes a massive difference and helps our exhausted organizers get home a
    little earlier. We truly appreciate the community effort!
  </p>
</div>
  
<div class="section">
  <h2>The Hero Force</h2>
  
  <p>
    If you've volunteered for the <strong>Hero Force</strong>, your assigned shifts are listed in your program and the app.
  </p>
  
  <p>
    If you already know that you won't be able to show up for your task, please email the Hero Force coordinators at
    <a href="mailto:heltestyrken@fastaval.dk">heltestyrken@fastaval.dk</a> and we'll find a solution.
  </p>
  
  <p>
    If, during Fastaval, you find yourself unable to perform your assignment after all, for example, due to illness,
    please let us know as soon as possible. That way, we'll have time to find someone to take over.
  </p>
  
  <p>
    You can reach Magnus and Christoffer, who are in charge of the Hero Force, at
    <strong>+45&nbsp;93&nbsp;90&nbsp;35&nbsp;68</strong> during Fastaval.
  </p>
</div>

<div class="section">
  <h2>Your Fastaval program</h2>
  
  <p>
    View your assigned activities, games, sleeping quarters, and hero tasks here:<br>
    <a href="https://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>">
      https://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>
    </a>
  </p>
  
  <p>
    Participant ID: <strong><?=$this->id?></strong><br>
  </p>
  
  <p>
    Personal Access Code: <strong><?=$this->code?></strong>
  </p>
  
  <p>
    Curious about what else is happening? Check out the full 
    <a href="https://docs.google.com/spreadsheets/d/1DsU-SWBdyOPAMXazmPqFEcWPc92qwVun">Fastaval <?=$this->year?> Program</a>.
  </p>
</div>

<div class="section">
  <h2>The Fastaval App</h2>
  
  <p>
    The app is your best friend during the con. It holds your schedule, meal tickets, room info, and maps. We use it to
    send out important updates, so we highly recommend downloading it! Log in using the same ID and code provided above.
  </p>
  
  <p>
    <a href="https://play.google.com/store/apps/details?id=dk.alea.fastaval.fastaval_app">Google Play</a> - 
    <a href="https://apps.apple.com/us/app/fastavappen/id6445799103">App Store</a>
  </p>
  
</div>

<div class="section">
  <h2>Finally</h2>
  
  <p>We can't wait to see you for an amazing Fastaval <?=$this->year?>!</p>
  
</div>

<img src="https://infosys.fastaval.dk/img/logo-plain-text.png" width="200" style="display: block; margin: auto;"/>

</div>